nextcloud/nextcloudpi

- etc/nextcloudpi-config.d/freeDNS.sh
This is an installation script for FreeDNS (http://freedns.afraid.org/) client for Raspbian. The client is basically a Bash script. It detects the difference in the registered IP on the record with the current IP address of the Raspbian board. If there is a difference, it runs a wget command and updates the record with the current IP address.
> Add FreeDNS (freedns.afraid.org) client installation for Raspbian

- update.sh
Update related to #289 
Instead of working on the symlink `/etc/apache2/sites-enabled/ncp.conf` we work directly with `/etc/apache2/sites-available/ncp.conf` This way if a user has disabled ncp-web - which removes the symlink that would resolve the files path - the operation still progresses without problems as intended.
> Using sites-available instead of sites-enabled

- etc/nextcloudpi-config.d/nc-datadir.sh
Two changes that make setting a new data directory integrate better with setting up fail2ban.
First change is a modification in the `sed` command. The jail.conf file has two logfile lines. One for the ssh and another for the nextcloud instance. The previous version changed both of them. The new one only changes the one that is for nextcloud.
The second change specifies the log directory in `config.php` when the data directory is changed from the default one. If it is not specified the log file will by default be placed within the data directory. The problem is that when a user installs fail2ban **after** he has moved the data directory then [this line](https://github.com/nextcloud/nextcloudpi/blob/4f63c349ab3c3ab935dfb7a41c2f88e0adc9eac4/etc/nextcloudpi-config.d/fail2ban.sh#L80) will …
> Fixed configuration interoperability between nc-datadit and fail2ban.

- etc/ncp-config.d/nc-rsync.sh
Changed rsync command to behave like nc-rsync-auto - as proposed in issue #686.
> nc-rsync.sh: sync datadir, not only content (#686)

- ncp-web/index.php
hover text for ncp admin header icon of "NextCloudPi Wizard" was broken.
> ncp-web: fixed hover text for ncp wizard icon

- etc/ncp-config.d/nc-backup.sh
As mentioned in [#685](https://github.com/nextcloud/nextcloudpi/issues/685#issuecomment-448632028) there is an inconsistency in the directory paths. 
I propose now another solution that will only affect the code if it is called inside docker.
For the `nextcloudpi-x86` configuration it is working and verified.
> fix: adapt DATADIR variable for prober nc-backup operation inside docker

- etc/ncp-config.d/nc-ramlogs.sh
This restores compatibility of the ncp app nc-ramlogs after the log2ram service was renamed on armbian.
> Check for unit name of log2ram service before enabling/disabling it.

- etc/ncp-config.d/DDNS_spDYN.sh
- update.sh
Change execution interval from once an hour to every five minutes.
> Update cron execution interval

- bin/ncp-update-nc
This PR implements the following:
1) check supported versions of all enabled NC apps for compatibility with the new version before an update
2) if incompatible apps are found, write their names and version requirements to the logs and abort the update
There is one potential issue with the update check: It's executed pre-update, that means, if an app does not support the next NC version, but it's update (which would support the next version) does not support the current NC version, there is no way for the updater to succeed.
Example: Assuming the currently supported version of the news app supports NC 12-14 and NC 15 is going to be installed. There is an update to the news app, which adds support for NC 15 but does not support any previous version. This will cause the update to not be able …
> check app compatibility before before executing NC update

- docker-common/debian-ncp/run-parts.sh
Proposed fix for issue #773. To recap:
> The regular expression on line 41 of `/run-parts.sh` appears to be incorrect: `grep 000*` will match any string contain either 000 _or_ 00. This means that when dnsmasq is enabled, for example, the startup service gets run twice, once after `000ncp` (which seems to be incorrect), and once with the other services (which appears to be the intention).
The changes here:
1. Fix this regular expression so that _only_ services starting with 000 are run during the setup phase, and
2. Tweak the process for identifying all other enabled services to parallel this first change.
I have been running this change "in production" on my personal NextCloudPi server for a bit over a week now, with no observable issues or errors.
(FWIW, this is the first pull request …
> Proposed fix for issue #773

- bin/ncp/NETWORKING/dnsmasq.sh
Proposed fix for issue #772. To recap:
> Right now, enabling `dnsmasq` within a NextCloudPi Docker container associates your `$DOMAIN` with the container's _private_ IP address. This means that Docker images cannot [use `dnsmasq` to redirect systems on your home network to your NextCloudPi server](https://ownyourbits.com/2017/03/09/dnsmasq-as-dns-cache-server-for-nextcloudpi-and-raspbian/).
This change sets the IP address corresponding to your Nextcloud `$DOMAIN` to the IP (optionally) passed into the docker image (which is stored by `020nextcloud` in `trusted_domains 6`). If `trusted_domains 6` is empty or is not an IP address, fall back to the previous behavior.
Tested on my "production" home NextCloudPi server. Note that I only have access to that server and a Chromebook right now, so …
> Proposed fix for issue #772

- update.sh
Test if `/etc/cron.*` directories have files before running `chmod` on them to prevent upgrade errors. Should fix #784.
> Proposed fix for #784

- bin/ncp-config
This fixes some warning reported on [a comment in one of my previous issues](https://github.com/nextcloud/nextcloudpi/issues/784#issuecomment-457483813). That said, this looks like a separate issue from what I reported.
Incidentally, this also makes the update prompt in `ncp-config` work for me (which it hadn't previously, but wasn't a big deal from my perspective).
I've _lightly_ tested this change on my own server, and haven't detected any bad consequences, but it's not 100% clear to me how much isolation you're trying to achieve here or if this tweak might break something subtle.
> Fixed warning + update prompt in ncp-config

- bin/ncp/BACKUPS/nc-rsync-auto.sh
- bin/ncp/BACKUPS/nc-rsync.sh
- etc/ncp-config.d/nc-rsync-auto.cfg
- etc/ncp-config.d/nc-rsync.cfg
This will allow the user to enter a ssh port number for rsync other than 22. Tried it with my external storage box that only allows connections over port 23. Not tested is the automatic rsync and also I'm not sure if the port causes problems for users that want to rsync to a local folder.
> nc-rsync: choose ssh port other than 22 (#564)

- bin/ncp/TOOLS/nc-maintenance.sh
- etc/ncp-config.d/nc-maintenance.cfg
This feature is designed for users who are just using nextcloud and can simply troubleshoot problems (such as accidentally opening maintenance mode when updating).
Thanks
> New features: Turn maintenance mode on or off

- bin/ncp/BACKUPS/nc-restore.sh
Recently I did a restore for the first time, by using NCP.
While I was reading that NCP is doing a backup (when I clicked "Restore a previously backuped NC instance"), I asked myself:
"Where will this backup be written to?"
This patch shows the user this info.
TanarRi
> Show the user more infos when backup the datadir

- bin/ncp/BACKUPS/nc-restore.sh
In case of restore a big nextcloud instance the current infos, showed the user is missleading.
Think of the steps:
1) echo "restore datadir to $DATADIR..." (info to the user)
2)  echo "backing up existing $DATADIR to $DATADIR-$( date "+%m-%d-%y" )..." (--> Info for the user: a backup is performed. Because it only renames a directory the move will last only 1 second)
3) ..no more infos for the user.... the user think: Well, the step 2 lasts a llooonnngggg time.... But the program is doing the real restore of the $DATADIR
--> moved the "echo" a few lines down...
TanarRi
>  Inform the user about the current step

- etc/ncp-config.d/SSH.cfg
'raspberry' is the password, and I think it should be quoted for better reading - like 'pi' a few words before in the same line.
> Small typo

- etc/ncp-config.d/nc-restore-snapshot.cfg
The info text says, that a snapshot will be "taken". That is wrong!
We are in restore-mode --> a snapshot will be "restored"
> Info text corrected

- etc/ncp-config.d/nc-passwd.cfg
Found a few reference https://github.com/nextcloud/nextcloudpi/issues/155 
to issues with special characters in passwords, also with german umlaut ".
Which ones are sanitized? and need to be added to "info" or should it be in "description"?
I will also add it to Config-Reference, once established which characters to avoid ;-)
> Clarify usage

- bin/ncp/CONFIG/nc-datadir.sh
- bin/ncp/TOOLS/nc-fix-permissions.sh
- bin/ncp/TOOLS/nc-previews.sh
Sometimes "data dir" will be used to inform the user - and sometimes "data directory"
This will fix this, that "data directory"consistently be used.
> Adjust naming of "data dir" to "data directory" to be consistent

- CONTRIBUTING.md
The CONTRIBUTING.md file links were pointing to the old wiki on github.
Based on the URL I replaced them with the links from docs.nextcloudpi.com.
I was wondering if is possible to do pull requests for the doc.nextcloudpi.com as well?
If yes, maybe a link could be added in this file.
Thank you
> Replace links from github wiki to docs.nextcloudpi.com

- etc/ncp-config.d/nc-restore.cfg
It seems the default values are out of a test-installation and the formating got lost.
Correct this to the previous values.
> nc-restore.cfg: default values for BACKUPFILE

- etc/ncp-config.d/nc-automount.cfg
I think it should be "removing", because "extraction" make no sense in automounting
> nc-automount.cfg: Update description

- update.sh
The update script only updates the NCP app at `/var/www/ncp-app` but not at `/var/www/nextcloud/apps/nextcloudpi`. This way it is not actually used by Nextcloud. This is fixed by this pull request.
> copy NCP app to nextcloud directory

- update.sh
When creating new images `update.sh` gets called. At this point Nextcloud is not yet fully installed and `thus app:enable` fails. This PR just remove this one line.
> do not enable nextcloud app in update script

- docker/nextcloudpi/Dockerfile
If you start an docker image via `docker` or `docker-compose` all ports which are exposed through inside the Dockerfile are always opened! The user cannot disable it.
See `sudo docker ps` after starting nextcloudpi-docker: Ports 80, 443 and 4443 are always exposed on the host.
This even bypasses the **UFW** setup on the host system as docker directly modifies the ip-tables. There exist some issues on the Docker repo discussing this problem. But the easiest "workaround" is not to force-expose any ports.
Launching the Docker image normally or via docker-compose should not be affected. If the user has for example 
```
ports:
- 80:80
- 443:443
- 4443:4443
```
included in his compose file, he won't notice this change.
What do you think of this? Is there any reason I missed for exposing the …
> Remove Expose Ports

- bin/ncp/SECURITY/modsecurity.sh
- update.sh
- updates/1.17.0.sh
- updates/1.17.1.sh
Temporary(?) fix to #959
Needs testing. I added functionality in `update.sh` to update the config for people who already have modsecurity running, please check that I haven't overlooked something (or misunderstood chow `check_distro` works). The intent is that the fix would only apply to people who are in buster and have enabled, at some point, modsecurity.
People who enable modsecurity for the first time get the updated config file.
> Increased modsecurity bodynofileslimit so larger files can be synced

- bin/ncp-provisioning.sh
- bin/ncp/CONFIG/nc-limits.sh
- docker/nextcloud/020nextcloud
I'm running ncp in docker.
This change fixed my problems with redis after updating.
Changing the redis.conf file leads to a permission change. This has to be reverted by the added command.
We also might have to change 
`bin/ncp/CONFIG/nc-nextcloud.sh`
since the file is adapted there as well.
fixes #1019
> fixing file permission for redis config

- bin/ncp-provisioning.sh
- bin/ncp/CONFIG/nc-limits.sh
- bin/ncp/NETWORKING/letsencrypt.sh
- docker/nextcloud/020nextcloud
- etc/ncp-config.d/letsencrypt.cfg
The ncp letsencrypt app now allows a second domain to be specified.
Fix: #837
> Letsencrypt: support second domain

- ncp.sh
If user already exists, useradd ends with error and terminates the whole instalation process.
> Add user only if it does not exist.

- etc/ncp-config.d/nc-backup.cfg
What seems obvious to us, may be unclear for 1st timers ;-)
People ask about this and backups in general.
> Add more info to description of nc-backup.cnf

- bin/ncp/UPDATES/nc-autoupdate-ncp.sh
Cronjobs should not have any output, unless the cronjob fails, otherwise an e-mail notification is sent with the output. This cronjob in particular is also reporting results via Nextcloud notification, so having an e-mail with logs saying the same as the notification is not particularly useful. Instead we just redirect all output to the /var/log/ncp.log so the user can debug in case of problems and doesn't receive spurious e-mails when all works fine.
> Make ncp-autoupdate cronjob write to the log

- bin/ncp/BACKUPS/nc-backup-auto.sh
Make sure the script don't return an exit status different from 0 so the
cron job doesn't send e-mails on failure, as notifications are being
delivered as Nextcloud notifications. Also redirect all output to a log
file, so in case of failure it is possible to review what happened.
This also makes the notification a bit more informative, as it says
which script failed.
The log files is overwritten on each run. This should not be a problem
since backups are run more frequently than once per day, so there should
be a fair amount of time to see the backup logs.
> Don't fail ncp-backup-auto

- bin/ncp/CONFIG/nc-database.sh
While reading through nc-database.sh, I thought that it might make sense to set the NO_COW flag on the db directory with chattr +C (because cow is not useful on large binary files and can heavily reduce performance).
This PR does precisely that. :)
I'm not entirely sure what happens when creating a btrfs snapshot, though. @nachoparker Do you think it might cause any issues?
> Exclude database directory from COW (on btrfs partitions)

- bin/ncp/CONFIG/nc-nextcloud.sh
- bin/ncp/NETWORKING/letsencrypt.sh
- bin/ncp/SYSTEM/metrics.sh
- etc/library.sh
- etc/ncp-config.d/metrics.cfg
- etc/ncp-templates/nextcloud.conf.sh
- etc/ncp-templates/prometheus-node-exporter.defaults
- update.sh
- updates/1.36.4.sh
Adds an ncp-app 'metrics' that exposes a prometheus compatible endpoint at https://[nc-domain]:443/metrics/system using [Prometheus Node Exporter](https://prometheus.io/docs/guides/node-exporter/)
❌ ~Docker support?~
**EDIT 1**: Probably not going to add docker support for now, since
1. It's not as easy to do as I hoped
2. Many metrics wouldn't work anyways without adjusting container privileges
3. It's not hard to install on the host
```
metrics.{sh,cfg}: Implement ncp-app for prometheus (system) metrics
letsencrypts.sh, nc-nextcloud.sh, nextcloud.conf.sh: Introduce templating/generator concept to allow multiple ncp apps to edit the same file without conflicts
library.sh: Add convenience function find_app_param
```
> [complete] Implement ncp-app for prometheus (system) metrics

- etc/ncp-config.d/nc-notify-updates.cfg
- etc/ncp-config.d/nc-update-nc-apps-auto.cfg
remove unused USER variable from ncp apps nc-notify-updates and nc-update-nc-apps-auto
> remove unused USER variable from ncp apps nc-notify-updates and nc-update-nc-apps-auto

- etc/ncp-config.d/nc-previews-auto.cfg
At first glance, I thought that "runtime" cloud be used to specify the time when the cron job starts. Had to look at the source code to confirm what the value actually means. Hope this change makes the command easier to understand. :slightly_smiling_face:
> Clarify documentation of nc-previews-auto command

- updates/1.46.0.sh
Fixes #1397 
I've opted to systemd path monitoring for non-docker versions, as that is fit better for the job (will fix the situation quicker and not restart constantly if there is another issue with notify_push).
For the latter reason, I've also set up the cron job for the docker version to run just daily and not more frequent.
From my perspective, this can be merged. @nachoparker do you have any objections?
> notify_push: fix service not restarting on binary update

- updates/1.46.0.sh
The script previously used `[[ ! -f /.docker-image ]] && { ... }` as its last statement, which returns non-zero in docker (as it should), but this exit code is then used as the over-all exit code of the update script, thus failing the update whenever used in docker container. Fixed by adding the same `exit 0` that's already there in all other update-scripts. Fixes issue #1405
Also removed a quote that I'm _pretty_ sure shouldn't be there.
> fix update from pre-1.46 to post-1.46 not working in docker

- bin/ncp-dist-upgrade
> ncp-dist-upgrade: Fix invalid target for apt-get on Raspbian

- index.html
Removed the identifier URL, in case this was the issue with the CA certificate from GitHub for https://nextcloudpi.com/
Signed-off-by: Zendai Owl <victorray91@pm.me>
> ࿓❯ Removed Identifier URL

- bin/ncp-update-nc
- bin/ncp/CONFIG/nc-init.sh
- etc/library.sh
- updates/1.43.0.sh
To determine if the Debian edition hosting NextCloud is 32 or 64 bit, NCP uses ``uname -m``.  This is mostly fine until you have (for example) a kernel reporting ``aarch64`` that is running Debian ``armhf`` in a container, whereupon the wheels fall off and scripts break.
As opposed to asking the Kernel, it's more reliable to ask the distro if NextCloud is 32 (armv7l, armv8l) or 64 (aarch64) bit to account for all possible hardware setups.
> Fix 32/64 bit architecture detection

- bin/ncp-diag
ncp-report searches for "gateway" to replace IP with "REMOVED SENSITIVE VALUE"
Signed-off-by: Jürgen <55851807+schoetju@users.noreply.github.com>
> gateway instead of Gateway (as ncp-report looks for this)

- bin/ncp/NETWORKING/SSH.sh
- build/build-SD-rpi.sh
- etc/ncp-config.d/dnsmasq.cfg
Fixes #1595 by:
- Reenabling pi user if used in ncp-config/SSH
- Setting ncp user as default in ncp-config/SSH
> SSH.sh: Reenable pi user if selected in SSH

- ncp-web/index.php
**Resolved / Related Issues**
- Closes: https://github.com/nextcloud/nextcloudpi/issues/1571
**Comments**
- Updated main logo to re-direct to https://nextcloudpi.com
- Updated right-side header logo to re-direct to https://nextcloudpi.com
- Updated information logo to re-direct to "https://docs.nextcloudpi.com/" (https://github.com/nextcloud/nextcloudpi/wiki is not being used anymore)
> Fixed: Nextcloudpi icon pointing to ownyoursbits.com

- bin/ncp-update-nc
Improves docker compatibility. Placing the backup file in /var/www/ will cause a failure in rolling back the update on containerized setups ("Can only restore from ext/btrfs/zfs filesystems"). The host filesystem is most likely compatible so using $BASEDIR as the backup location *should* solve this issue for most users.
Signed-off-by: MB-Finski <64466176+MB-Finski@users.noreply.github.com>
> Temporarily place backup to BASEDIR

- bin/ncp-update-nc
Improve docker compatibility of "ncp-update-nc.sh" script: Change the backup directory for ./nextcloud/data to reside within the host file system (basedir) so as to avoid moving the data folder back and forth between the docker container and the host file system (results in copying the whole data folder). In situations where the nextcloud data takes up more than the free available space on the host system, this may lead to loss of data.
Signed-off-by: MB-Finski <64466176+MB-Finski@users.noreply.github.com>
> Change backup directory for docker compatibility

- update.sh
Fixes the extra forward slash that gets introduced in the various paths inside the update.sh file.  
Signed-off-by: Victor-ray, S <12261439+ZendaiOwl@users.noreply.github.com>
> ࿓❯ Removed the extra forward slash in the config directory variable

- bin/ncp-update-nc
Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>
> [fix] ncp-update-nc: Don't remove systemd during PHP rollback

- bin/ncp/NETWORKING/SSH.sh
࿓❯ SSH.sh: Rewrote SSH activation so it allows for user creation and disallows the webadmin to be used
Signed-off-by: Victor-ray, S <12261439+ZendaiOwl@users.noreply.github.com>
> ࿓❯ SSH.sh: Rewrote SSH activation to allow user creation 

- .github/workflows/build-lxd.yml
- .github/workflows/release.yml
- bin/nc-broadcast
- bin/ncp/NETWORKING/SSH.sh
- bin/ncp/SECURITY/fail2ban.sh
- build/docker/debian-ncp/run-parts.sh
- etc/ncp-templates/ncp-metrics.cfg.sh
- ncp.sh
- update.sh
- Converts the generated LXD images to LXC compatible ones and adds them as CICD pipeline artefacts.
- Enables a number of apps for LXC/LXD containers (needs more testing):
- Disables user locking for containers
- Adds the utility cli tool `nc-broadcast` for sending notifications to all Nextcloud users
> Build LXC images in CICD pipeline

- bin/ncp/CONFIG/nc-limits.sh
- etc/ncp-config.d/nc-limits.cfg
- etc/ncp-templates/php/pool.d.www.conf.sh
Like described in issue https://github.com/nextcloud/nextcloudpi/issues/1624
the default for php.ini setting pm.max_children has been improved to be equal total_mem / 100 MB but 16 at minimum.
> Improved default for php max children

- README.md
Removed the Docker information from the README
Signed-off-by: Victor-ray, S <owl@zendai.net.eu.org>
> ࿓❯ fix: Removed Docker information from README

- bin/ncp-update-nc
This fixes issue #1818 by getting the database prefix from the configuration file and using it in the SQL command that failed because of a hard coded database prefix.
> Fix database prefix
