- etc/nextcloudpi-config.d/nc-nextcloud.sh
If BETA=yes it adds "pre"  to the download path. ${PREFIX}
Haven't tested this yet, will do so shortly after creating pull request
> Added option to install Beta

- install.sh
No need to introduce temp file vulnerabilities. I hope other scripts are not also affected and only checked this script since https://github.com/armbian/config/commit/b6d2249dff8df8826cb3280255aedf9919f5dff4#commitcomment-28910611
> Improve tempdir handling

- ncp-web/activate/index.php
I think someone else also made some changes to all the files, so this may be duplication.  This is my very first pull request.  No issue with rejecting it for duplication, but let me know if I did everything correctly.
> I've updated the Activate web page changing NextCloudPlus back to NextCloudPi

- bin/ncp-diag
just copied some code from nc-database.
> Added database dir to ncp-diag

- update.sh
PR sent following our discussion in #566
> Fixes #566 Remove redundant opcache configuration

- etc/ncp-config.d/DDNS_spDYN.sh
With these fixes it does work correctly with both IPv4 and IPv6 on my installation.
> Two variable fixes in DDNS_spDYN.sh

- etc/ncp-config.d/nc-database.sh
Following request from user 'wayneoutthere' for more clarity from https://github.com/nextcloud/nextcloudpi/issues/707
> Update info field to clarify usage

- etc/ncp-config.d/nc-datadir.sh
Following request from user wayneoutthere https://github.com/nextcloud/nextcloudpi/issues/707
@nachoparker let me know if this is the correct way to add to the code: meaning doing pull request against devel?
> Clarify usage under info

- install.sh
More relevant info to what steps one should take.
Should I add same to end of nc-init? Would be nice to have variable that grabs and fills in the your_IP?
> Update echo at end when init done.

- README.md
> Update Docker links

- etc/ncp-config.d/nc-datadir.cfg
Some users do not see this as obvious ;-)
> Add SATA to description

- README-ZH-TW.md
- README.md
Resend. This time the Nextcloud 14.03 was revised to 15.04. and remove unnecessary files.
@nachoparker
> add readme chinese translate

- etc/ncp-config.d/nc-restore.cfg
'nc-backup' is the name of the program
> Small typo

- README-ZH-TW.md
> Update Readme zh-tw

- etc/ncp-config.d/freeDNS.cfg
- etc/ncp-config.d/nc-backup-auto.cfg
- etc/ncp-config.d/nc-backup.cfg
- etc/ncp-config.d/nc-previews-auto.cfg
- etc/ncp-config.d/nc-rsync-auto.cfg
- etc/ncp-config.d/nc-scan-auto.cfg
- etc/ncp-config.d/nc-snapshot-sync.cfg
> Rename configuration variables into self-documenting ones

- bin/ncp/BACKUPS/nc-rsync-auto.sh
- bin/ncp/SYSTEM/nc-ramlogs.sh
- update.sh
Closes #979
Signed-off-by: benne <2770597+stratmaster@users.noreply.github.com>
> Add missing port in nc-rsync-auto.sh

- update.sh
Fix for bug mentioned [here](https://github.com/nextcloud/nextcloudpi/issues/416#issuecomment-554265996).
> Fix for reappearing opcache bug.

- bin/ncp/CONFIG/nc-trusted-proxies.sh
- etc/ncp-config.d/nc-trusted-proxies.cfg
Signed-off-by: paschaef <45995338+paschaef@users.noreply.github.com>
As mentioned in #1092
> feat: Add trusted proxies manually to NCP

- bin/ncp/NETWORKING/samba.sh
- etc/ncp-config.d/samba.cfg
Implements #1047
At this point this is a quickly thrown together (untested!) implementation (10min effort :P ).
I'll iron it out in the coming days if Nacho likes the approach.
> SAMBA - filter by group option

- bin/ncp-diag
> - fixed api change for portchecker

- bin/ncp/BACKUPS/nc-backup-auto.sh
append to log instead of clearing it
see https://github.com/nextcloud/nextcloudpi/issues/1232#issuecomment-891524543
> Update nc-backup-auto.sh to append to ncp.log instead of clearing it

- .github/workflows/build-docker.yml
- .github/workflows/build-lxd.yml
- .github/workflows/lxd-trigger.yml
- .github/workflows/pr-tests.yml
- bin/ncp-diag
- bin/ncp-update
- bin/ncp-update-nc
- bin/ncp/CONFIG/nc-datadir.sh
- bin/ncp/CONFIG/nc-init.sh
- bin/ncp/SYSTEM/metrics.sh
- etc/library.sh
- updates/1.43.0.sh
> Minor fixes

- README.md
Signed-off-by: Florian Wallner <asdf@walura.eu>
> Update the Nextcloud version number to 24.0.3 in Readme

- bin/ncp-diag
Signed-off-by: Jürgen <55851807+schoetju@users.noreply.github.com>
> gateway instead of Gateway (as ncp-report looks for this)

- build/docker/debian-ncp/run-parts.sh
Signed-off-by: thecalcaholic <6317548+theCalcaholic@users.noreply.github.com>
Merging the changes into containerize branch
Signed-off-by: Zendai Owl <12261439+ZendaiOwl@users.noreply.github.com>
> run-parts.sh: Prevent mariadb to start with /data-ro/* as db dir

- update.sh
Signed-off-by: thecalcaholic <6317548+theCalcaholic@users.noreply.github.com>
Signed-off-by: Zendai Owl <12261439+ZendaiOwl@users.noreply.github.com>
> update.sh: Prevent ncp-update on older docker containers

- ncp.sh
> ࿓❯ Fixed ncp.sh

- .github/workflows/build-docker.yml
- .github/workflows/build-lxd.yml
- .github/workflows/lxd-trigger.yml
- README.md
- etc/ncp-config.d/nc-nextcloud.cfg
- etc/ncp.cfg
- ncp-app/appinfo/info.xml
- ncp-previewgenerator/ncp-previewgenerator-nc21/appinfo/info.xml
> Add support for Nextcloud 25.0.2

- README.md
Signed-off-by: Victor-ray, S <12261439+ZendaiOwl@users.noreply.github.com>
> ࿓❯ Update README

- bin/ncp-update-nc
- bin/ncp/UPDATES/nc-update-nextcloud.sh
- build/docker/Dockerfile
- build/docker/debian-ncp/run-parts.sh
Fixes #1715
Fixes #1633
Fixes #1694
> Fix various issues related to updating Nextcloud

- .github/workflows/release.yml
- bin/ncp/BACKUPS/nc-rsync-auto.sh
- bin/ncp/BACKUPS/nc-snapshot-sync.sh
- etc/ncp-config.d/nc-rsync-auto.cfg
- etc/ncp-config.d/nc-snapshot-sync.cfg
- updates/1.51.1.sh
Add option to configure hour for Auto Backup, Auto RSync and Auto Snapshot via WebUI
Implements #1690 and #1623
> Let users configure Hour of Backups / Sync

- bin/ncp/TOOLS/nc-format-USB.sh
Fix typo in flag variable, which rendered the entire feature useless in certain situations.
> Fix bug in nc-format-USB.sh

- bin/ncp/CONFIG/nc-previews-auto.sh
- updates/1.55.0.sh
Fix typo that prevents the feature from being disabled.
> Fix bug in nc-previews-auto.sh

- bin/ncp/TOOLS/db-optimize.sh
- etc/ncp-config.d/db-optimize.cfg
Enables the user to do a database optimization from NextcloudPi UI like mentioned in 
https://github.com/nextcloud/nextcloudpi/issues/989
> Optimize database

- bin/ncp-update-nc
> ncp update nc as oneshot
